import { CustomDialog } from "@/components/common/CustomDialog"
import { useTranslations } from "next-intl";
import { useState } from "react";
import { HiPlus } from "react-icons/hi2";
import { Form } from "@/components/ui/form";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import _eventFormSchema from "@/forms/sg/eventFormSchema";
import z from "zod";
import { AppModulesTicketingSchemasTicketingEventComplete, postTicketingEvents, StoreSimple } from "@/api";
import { useToast } from "@/components/ui/use-toast";
import { AddEditEventForm } from "@/components/sg/admin/AddEditEventForm";

import  { useEvents } from "@/hooks/sg/useEvents";
import { error } from "console";

interface AddEventAccordionItemProps {
  creatorId: string;
  refreshEvent: () => void;
}

export const AddEventAccordionItem = ({ 
    creatorId,
    refreshEvent
}: AddEventAccordionItemProps) => {
    const tZod =  useTranslations("sg.eventFormSchema");
    const [isAddDialogOpened, setIsAddDialogOpened] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();
    const { refetch: refetchEvents, postEvent } = useEvents();
    const t = useTranslations("sg");

    const eventFormSchema = _eventFormSchema(tZod);

    const form = useForm<z.infer<typeof eventFormSchema>>({
        resolver: zodResolver(eventFormSchema),
        mode: "onBlur",
        defaultValues: {
            name: "",
            creator_id: creatorId,
            store_id: "",
            open_date: new Date(),
            close_date: new Date(),
            user_quota: 0,
            quota: 0,
            disabled: false,

        },
      });

    async function onSubmit(values: z.infer<typeof eventFormSchema>) {
        setIsLoading(true);
        console.log("Submitting form values:", values);
        const body: AppModulesTicketingSchemasTicketingEventComplete = {
            ...values,
            id: "", // The ID will be generated by the backend, so we can set it to an empty string or omit it
            user_quota: Number(values.user_quota),
            open_date: values.open_date.toISOString(),
            close_date: values.close_date.toISOString(),
            used_quota: 0,
            sessions: [],
            categories: [],
            store: {
                name: "",
                id: values.store_id,
                structure_id: "",
                wallet_id: "",
                creation: new Date().toISOString(),
            } as StoreSimple,
            };

          
        postEvent(body, () => {
            refetchEvents();
            setIsAddDialogOpened(false);
            setIsLoading(false);
            form.reset();
        });


      }

    return (
        <CustomDialog
            title={t("addEventDialogTitle.newEvent")}
            description={
                <Form {...form}>
                    <form onSubmit={form.handleSubmit(onSubmit)}>
                        <AddEditEventForm
                            form={form}
                            setIsOpened={setIsAddDialogOpened}
                            isLoading={isLoading}
                            creatorId={creatorId}
                        />
                    </form>
                </Form>
            }
            isOpened={isAddDialogOpened}
            setIsOpened={setIsAddDialogOpened}
        >

            <div className="border rounded-lg p-4">
                <HiPlus className="w-4 h-4 mr-6" />
                <h3 className="text-lg font-semibold mb-2">Ajouter un événement</h3>

                <div className="flex grow"></div>
            </div>
        </CustomDialog>

)}

